### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by bedroesb**
This should fix the problem that was causing the docker build to fail.

### CODE REVIEW

**Comment by bedroesb** [comment]
it seems that https://www.eu-sol.wur.nl/webapi/tomato/brapi/v1 is down ...

**Comment by erikkimmel** [comment]
All seems to be ok for me.
Best

**Comment by bedroesb** [comment]
@erikkimmel if isatools 13.0 gets fully released (on pypi) we can updte the dependencies to 13.0. Would it btw not be nice to release this tool on pypi too?

**Comment by erikkimmel** [comment]
@bedroesb you're right.

**Pull request merged**
