### PR TITLE
New config files + more MIAPPE compliant 

### PR DESCRIPTION
**Pull request by bedroesb**
To make some columns visible in the assay file, I had to add a string instead of "" as term.
These are values that can not be filled in with BrAPI, So I filled it in with "NA in BrAPI"

Current status of assay file:

| Sample Name | Protocol REF | Parameter Value[Collection Date] | Parameter Value[Sample Description] | Assay Name | Raw Data File | Protocol REF        | Derived Data File          |
|-------------|--------------|----------------------------------|-------------------------------------|------------|---------------|---------------------|----------------------------|
| pot_1       | Phenotyping  | NA in BrAPI                      | NA in BrAPI                         | P_9327     | NA            | Data Transformation | d_VIB_study___55_plant.txt |
| pot_10      | Phenotyping  | NA in BrAPI                      | NA in BrAPI                         | P_9336     | NA            | Data Transformation | d_VIB_study___55_plant.txt |
| pot_100     | Phenotyping  | NA in BrAPI                      | NA in BrAPI                         | P_9426     | NA            | Data Transformation | d_VIB_study___55_plant.txt |
| pot_101     | Phenotyping  | NA in BrAPI                      | NA in BrAPI                         | P_9427     | NA            | Data Transformation | d_VIB_study___55_plant.txt |
| pot_102     | Phenotyping  | NA in BrAPI                      | NA in BrAPI                         | P_9428     | NA            | Data Transformation | d_VIB_study___55_plant.txt |

In this PR I will also try to fix following warnings:
- [x] Investigation Person Address 

- [x] Protocol(s) of type ['Growth'] defined in the ISA-configuration expected as a between 'Source Name' and 'Sample Name' but has not been found, in the file 's_VIB_study___55.txt'"

- [ ] Protocol(s) of type ['Sampling', 'Phenotyping'] defined in the ISA-configuration expected as a between 'Sample Name' and 'Assay Name' but has not been found, in the file 'a_VIB_study___55_plant.txt'",

- [x] protocols declared in the file s_VIB_study___55.txt are not used in any assay file: {'Data Transformation'

- [x] Protocol(s) of type ['Data Transformation'] defined in the ISA-configuration expected as a between 'Raw Data File' and 'Derived Data File' but has not been found, in the file 'a_VIB_study___55_plant.txt'

- [x] Some protocol parameters referenced in an assay file a_VIB_study___55_plant.txt are not declared in the investigation file: ['Collection Date', 'Sample Description']

- [x] 'Could not resolve Protocol parameter from Parameter Value ', 'Collection Date'

+ add MIAPPE attributes not available in BrAPI:

issue #48

### CODE REVIEW

**Comment by bedroesb** [comment]
I also broke the ISA-tab to ISA JSON conversion :)

**Comment by proccaserra** [comment]
> I also broke the ISA-tab to ISA JSON conversion :)

Do you get an error message? 
Looking at the ISA-Tab, `Derived Data File` should not be found before `Raw Data File`

**Comment by bedroesb** [comment]
@proccaserra 

```
Could not resolve Protocol parameter from Parameter Value ', 'Collection Date'
```
I get this error is linked to :
```
Some protocol parameters referenced in an assay file a_VIB_study___55_plant.txt are not declared in the investigation file: ['Collection Date', 'Sample Description']
```
So if I declare the protocols correctly, I might fix everything

**Comment by proccaserra** [comment]
@bedroesb the protocol thingy should be straightforward to address but please make sure to re-order the `files` headers. First `Raw` then `Derived`. best.

**Comment by bedroesb** [comment]
@proccaserra Ok I re-ordered them. I just had a question. How do I add a protocol parameter in the investigation file? This to solve the error `Some protocol parameters referenced in an assay file a_VIB_study___55_plant.txt are not declared in the investigation file: ['Sample Description', 'Collection Date']` Thank you

**Comment by proccaserra** [comment]
@bedroesb sorry got quite busy, but if you do the following:

from isatools.model import *

...

#### Make sure you have created a protocol.
sample_collection_protocol = Protocol(
            name="sample collection-TEST",
            protocol_type=OntologyAnnotation(term="sample collection-TEST"))

##### in a 2 step process and create a ```protocolParameter``` object, and note how the ```parameter_name ``` argument  of the ```ProtocolParameter```  has to  receive an OntologyAnnotopn
param1 = ProtocolParameter(parameter_name=OntologyAnnotation(term="Collection Date"))
sample_collection_protocol.parameters.append(param1)
 
##### you can also do it in one go:   sample_collection_protocol.parameters.append(ProtocolParameter(parameter_name=OntologyAnnotation("material description")))

sample_collection_protocol.parameters.append(ProtocolParameter(parameter_name="Sample Description"))

#### Don't forget to append the newly created protocol to the study.
study.protocols.append(sample_collection_protocol)

hope this helps. best P

**Comment by bedroesb** [comment]
JSON Dump is fixed

**Comment by bedroesb** [comment]
@proccaserra thank you for the snippets, it was really helpful. 

Would it be possible to give me a similar example to solve following warning:

"message": "Missing Protocol declaration",
            "supplemental": "Protocol(s) of type ['Data Transformation'] defined in the ISA-configuration expected as a between 'Raw Data File' and 'Derived Data File' but has not been found, in the file 'a_VIB_study___55_plant.txt'",
            "code": 1007
The protocol is declared and seen in the investigation file, but I should be able to place it between raw data and derived data file.

**Comment by bedroesb** [comment]
Added Data Transformation process, but lost the raw data file column

**Comment by proccaserra** [comment]
@bedroesb I think you are the missing the output of the Phenotyping Process.
input  = material instance
output =  Raw Data File instance

currently: the output is
https://github.com/elixir-europe/plant-brapi-to-isa/blob/refactoring/brapi_to_isa.py#L210

Then:

Data transformation process will have:
input = Raw Data File instance
output = Derived Data File instance

without forgetting the 'plink':
plink(sampling_process, phenotyping_process)
plink(phenotyping_process, data_transformation_process)

as per your email:

# Data Transformation
 data_transformation_process = Process(executes_protocol=data_transformation_protocol)

 # Adding Raw Data File column
 RAW_datafile = DataFile(filename="NA in BrAPI", label="Raw Data File", generated_from=[this_isa_sample])
 data_transformation_process.inputs.append(RAW_datafile)
 
 # Adding Derived Data File column
 datafilename = 'd_' + str(brapi_study_id) + '_' + att_test(obs_unit, 'observationLevel', "study") + '.txt'
 DER_datafile = DataFile(filename=datafilename, label="Derived Data File")
 data_transformation_process.outputs.append(DER_datafile)
 
 isa_study.assays[i].process_sequence.append(data_transformation_process)
 plink(phenotyping_process, data_transformation_process)

**Comment by bedroesb** [comment]
@proccaserra Ok it is working ! nice, I am starting to understand the whole process usage, Thank you very much.

**Pull request merged**
