### PR TITLE
Trait definition file improvement

### PR DESCRIPTION
**Pull request by bedroesb**
## Examples:

t_RIGW1.txt:

| Variable ID    | Variable Name  | Trait                                            | Method          | Method Description     | Scale         | Time Scale |
|----------------|----------------|--------------------------------------------------|-----------------|------------------------|---------------|------------|
| CO_356:1000001 | BUD_DATE       | Budbreak                                         | BUD_DATE Method |                        | Calendar date | Time       |
| CO_356:1000010 | VER_50         | Veraison                                         | VER_50 Method   |                        | Calendar date | Time       |
| CO_356:1000011 | FLO_50         | Flowering                                        | FLO_50 Method   |                        | Calendar date | Time       |
| CO_356:1000053 | BERRY_TOTATERP | Concentrations of free and bound alpha-terpineol | SPE             | Solid Phase Extraction | microg/kg     | Numerical  |
| CO_356:1000054 | BERRY_TOTCITRO | Concentrations of free and bound citronellol     | SPE             | Solid Phase Extraction | microg/kg     | Numerical  |
| CO_356:1000055 | BERRY_TOTGERAN | Concentrations of free and bound geraniol        | SPE             | Solid Phase Extraction | microg/kg     | Numerical  |
| CO_356:1000056 | BERRY_TOTLIN   | Concentrations of free and bound linalool        | SPE             | Solid Phase Extraction | microg/kg     | Numerical  |
| CO_356:1000057 | BERRY_TOTNER   | Concentrations of free and bound nerol           | SPE             | Solid Phase Extraction | microg/kg     | Numerical  |

t_POPYOMICS-POP2-F.txt:

| Variable ID    | Variable Name | Trait                    | Method                       | Method Description                                                                                                                                                              | Reference Associated to the Method                                                                                                                            | Scale                              | Time Scale |
|----------------|---------------|--------------------------|------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------|------------|
| CO_357:0000010 | BF_score_BL   | Budflush                 | Budflush scoring protocol    | Visual assessment on the terminal bud or on the whole tree when terminal bud is not visible with a reference scoring scale                                                      | https://forgemia.inra.fr/urgi-is/ontologies/blob/develop/Tree/T4F_D21_submitted.pdf - pages 6-20 + 30-35 for broadleaves and 45-49 + 62-64 for conifers       | Broadleaves budflush scoring scale | Nominal    |
| CO_357:0000010 | BF_score_BL   | Débourrement             | Protocole score débourrement | Evaluation à l'oeil nu selon une échelle de notation de référence sur le bourgeon apical (ou supposé apical) ou sur l'arbre entier lorsque le bourgeon apical n'est pas visible | https://forgemia.inra.fr/urgi-is/ontologies/blob/develop/Tree/T4F_D21_submitted.pdf - pages 6-20 + 30-35 pour les feuillus et 45-49 + 62-64 pour les conifers | Note de débourrement feuillus      | Nominal    |
| CO_357:0000016 | BS_date       | Budset date              | Bud date protocol            | Estimated date from polynomial regression of a time series of budflush or budset scores                                                                                         |                                                                                                                                                               | Calendar day                       | Date       |
| CO_357:0000016 | BS_date       | Date d'aoûtement         | Protocole date bourgeon      | Estimation de la date d'après une régression polynomiale réalisée sur une série temporelle de scores de débourrement ou bourgeonement                                           |                                                                                                                                                               | Jour calendaire                    | Date       |
| CO_357:0000020 | CIR1          | Tree circumference       | Ribbon 1m protocol           | Measured at 1m from the ground with a graduated ribbon                                                                                                                          | http://www.csdhub.com/national-plant-specification/conifers/nps-conifers-girth/                                                                               | mm                                 | Numerical  |
| CO_357:0000020 | CIR1          | Circonférence de l'arbre | Protocole ruban 1m           | Mesuré à 1m avec un ruban souple gradué en millimètres                                                                                                                          | http://www.csdhub.com/national-plant-specification/conifers/nps-conifers-girth/                                                                               | mm                                 | Numerical  |

t_VIB_study___40.txt:

| Variable ID | Variable Name              | Trait                      | Method                     | Method Description                                                                                              | Scale | Time Scale |
|-------------|----------------------------|----------------------------|----------------------------|-----------------------------------------------------------------------------------------------------------------|-------|------------|
| 188         | cellDivisionZoneLengthLeaf | cellDivisionZoneLengthLeaf | cellDivisionZoneLengthLeaf | size of the cell division zone at the basis of a leaf                                                           | mm    | numeric    |
| 195         | finalLeafLength            | finalLeafLength            | finalLeafLength            | length of a leaf at the end of its elongation                                                                   | mm    | numeric    |
| 60          | leafArea                   | leafArea                   | leafArea                   | a leaf anatomy and morphology trait (TO:0000748) which is associated with the total area of a leaf (PO:0025034) | mm2   | numeric    |

t_BTH_Dijon_2005_SetB1.txt:

| Variable ID  | Variable Name | Trait        | Method         | Method Description                                        | Scale | Time Scale |
|--------------|---------------|--------------|----------------|-----------------------------------------------------------|-------|------------|
| WIPO:0000074 | GY_q/ha       | Grain yield  | Direct measure | Mesure directe # ModeOp Arvalis = Récolte machine  RDT 0% | q/ha  | Numerical  |
| WIPO:0000218 | ht            | Plant height | ht             |                                                           | cm    | Numerical  |
| WIPO:0000219 | prec          | Precocity    | prec           |                                                           | d     | Duration   |
| WIPO:0000220 | ps            | Test weight  | ps             | Weight of 100 litres of grain.                            | kg/hl |            |

### CODE REVIEW

**Comment by bedroesb** [comment]
NO Term Source REF / Term Accesion Number implementation

**Comment by cpommier** [comment]
@bedroesb Did you had the opportunity to test with the wheat data set ? I remember there was a problem with TDF generation with treatments n the source.

**Comment by PapoutsoglouE** [comment]
I understand that the endpoints that are currently driving this implementation don't have all mandatory attributes. With that in mind, the above looks solid.  
Otherwise:
* implement othe `term source ref`/`accession number` columns, as stated
* for all of the above, the `variable ID` is essentially what various crop ontologies call "variable name" - see [here](http://www.cropontology.org/terms/CO_322:0000794/) for example. I can see the confusion... In general, when in doubt, it's a good idea to consult the current version of the standard itself. In turn, the `variable name` here is supposed to be more human-readable, since it is the only non-ID, free-text field for the variable itself. I don't know which BrAPI fields are being used for this, so it may or may not be worth adjusting.
* the `time scale` field is not being used as intended. Per the MIAPPE definition, it is the:
    > Name of the scale or unit of time with which observations of this type were recorded in the data file (for time series studies). 

    and possible values for it include date/time and growing degree days. Also bear in mind that it is not mandatory.

**Comment by bedroesb** [comment]
@cpommier ye, I've added an example of the wheat dataset. I rewrote the whole tdf generation part.

**Comment by bedroesb** [comment]
@PapoutsoglouE Updated the examples

**Pull request merged**
